from tkinter import PhotoImage


class Imagens:
    def __init__(self):
        self.img_bg = PhotoImage(
            file='assets/base_background.png')
        self.img_base_s1 = PhotoImage(
            file='assets/log_reg.png')
        self.img_bt_rg = PhotoImage(
            file='assets/bt_regist.png')
        self.img_bt_log = PhotoImage(
            file='assets/bt_log.png')
        self.img_log_text = PhotoImage(
            file='assets/login_text.png')
        self.img_bt_enter = PhotoImage(
            file='assets/bt_entrar.png')
        self.img_registro = PhotoImage(
            file='assets/registro_base.png')
        self.img_reg_text = PhotoImage(
            file='assets/Registro_text.png')
        self.bt_submit_registro = PhotoImage(
            file='assets/bt_registrar.png')
        self.bt_processador = PhotoImage(
            file='assets/bt_processador.png')
        self.bt_ram = PhotoImage(
            file='assets/bt_ram.png')
        self.bt_gpu = PhotoImage(
            file='assets/bt_gpu.png')
        self.bt_placa_mae = PhotoImage(
            file='assets/bt_pmae.png')
        self.bt_memoria2 = PhotoImage(
            file='assets/bt_ssdhdd.png')
        self.bt_fonte = PhotoImage(
            file='assets/bt_fonte.png')
        self.base_tela2 = PhotoImage(
            file='assets/frame_2.png')
        self.bt_I9_13900k = PhotoImage(
            file='assets/bt_I9_13900k.png')
        self.bt_I9_11900 = PhotoImage(
            file='assets/bt_I9_11900.png')
        self.bt_ryzen9_79000X = PhotoImage(
            file='assets/bt_ryzen9_79000X.png')
        self.bt_ryzen9_7950X30 = PhotoImage(
            file='assets/bt_ryzen9_7950X30.png')
        self.bt_carrinho = PhotoImage(
            file='assets/bt_carrinho.png')
        self.bt_ram_kingston = PhotoImage(
            file='assets/bt_ram_kingston.png')
        self.bt_ram_spectrix = PhotoImage(
            file='assets/bt_ram_spectrix.png')
        self.bt_ram_zadak = PhotoImage(
            file='assets/bt_ram_zadak.png')
        self.bt_ram_beast = PhotoImage(
            file='assets/bt_ram_beast.png')
        self.bt_gpu_rtx4090 = PhotoImage(
            file='assets/bt_gpu_rtx4090.png')
        self.bt_gpu_rtx3050 = PhotoImage(
            file='assets/bt_gpu_rtx3050.png')
        self.bt_gpu_rx7900 = PhotoImage(
            file='assets/bt_gpu_rx7900.png')
        self.bt_gpu_rx6650 = PhotoImage(
            file='assets/bt_gpu_rx6650.png')
        self.bt_pmae_b650 = PhotoImage(
            file='assets/bt_pmae_b650.png')
        self.bt_pmae_b550m = PhotoImage(
            file='assets/bt_pmae_b550m.png')
        self.bt_pmae_h610m = PhotoImage(
            file='assets/bt_pmae_h610m.png')
        self.bt_pmae_b560m = PhotoImage(
            file='assets/bt_pmae_b560m.png')
        self.bt_memoria2_wd = PhotoImage(
            file='assets/bt_memoria2_wd.png')
        self.bt_memoria2_wdblue = PhotoImage(
            file='assets/bt_memoria2_wdblue.png')
        self.bt_memoria2_ssdkingston = PhotoImage(
            file='assets/bt_memoria2_ssdkingston.png')
        self.bt_memoria2_ssdwd = PhotoImage(
            file='assets/bt_memoria2_ssdwd.png')
        self.bt_fonte_thermaltake = PhotoImage(
            file='assets/bt_fonte_thermaltake.png')
        self.bt_fonte_smart = PhotoImage(
            file='assets/bt_fonte_smart.png')
        self.bt_fonte_scoolerv3 = PhotoImage(
            file='assets/bt_fonte_scoolerv3.png')
        self.bt_fonte_reddragon = PhotoImage(
            file='assets/bt_fonte_reddragon.png')
        self.base_vendas = PhotoImage(
            file='assets/base_vendas.png')
        self.bt_mais = PhotoImage(
            file='assets/bt_mais.png')
        self.bt_menos = PhotoImage(
            file='assets/bt_menos.png')
        self.bt_add_carrinho = PhotoImage(
            file='assets/bt_add_carrinho.png')
        self.bt_finalizar = PhotoImage(
            file='assets/bt_finalizar.png')
        self.i9_13900k = PhotoImage(
            file='assets/i9_13900k.png')
        self.i9_11900 = PhotoImage(
            file='assets/i9_11900.png')
        self.r9_79000x = PhotoImage(
            file='assets/r9_79000x.png')
        self.r9_7950x3d = PhotoImage(
            file='assets/r9_7950x3d.png')
        self.kingston_ddr4 = PhotoImage(
            file='assets/kingston_ddr4.png')
        self.xpg_ddr4 = PhotoImage(
            file='assets/xpg_ddr4.png')
        self.zadak_ddr5 = PhotoImage(
            file='assets/zadak_ddr5.png')
        self.kingston_ddr5 = PhotoImage(
            file='assets/kingston_ddr5.png')
        self.rtx_4090 = PhotoImage(
            file='assets/rtx_4090.png')
        self.rtx_3050 = PhotoImage(
            file='assets/rtx_3050.png')
        self.rx_7900xt = PhotoImage(
            file='assets/rx_7900xt.png')
        self.rx_6650xt = PhotoImage(
            file='assets/rx_6650xt.png')
        self.pmae_b650 = PhotoImage(
            file='assets/pmae_b650.png')
        self.pmae_b550m = PhotoImage(
            file='assets/pmae_b550m.png')
        self.pmae_h610m = PhotoImage(
            file='assets/pmae_h610m.png')
        self.pmae_b560m = PhotoImage(
            file='assets/pmae_b560m.png')
        self.hdd_purple = PhotoImage(
            file='assets/hdd_purple.png')
        self.hdd_blue = PhotoImage(
            file='assets/hdd_blue.png')
        self.ssd_kingston = PhotoImage(
            file='assets/ssd_kingston.png')
        self.ssd_green = PhotoImage(
            file='assets/ssd_green.png')
        self.f_thermaltake_t = PhotoImage(
            file='assets/f_thermaltake_t.png')
        self.f_thermaltake_s = PhotoImage(
            file='assets/f_thermaltake_s.png')
        self.f_scoolerm = PhotoImage(
            file='assets/f_scoolerm.png')
        self.f_reddragon = PhotoImage(
            file='assets/f_reddragon.png')
        self.c_100 = PhotoImage(
            file='assets/c_i9_13900k.png')
        self.c_101 = PhotoImage(
            file='assets/c_i9_11900.png')
        self.c_102 = PhotoImage(
            file='assets/c_r9_79000x.png')
        self.c_103 = PhotoImage(
            file='assets/c_r9_7950x3d.png')
        self.c_200 = PhotoImage(
            file='assets/c_kingston_ddr4.png')
        self.c_201 = PhotoImage(
            file='assets/c_xpg_ddr4.png')
        self.c_202 = PhotoImage(
            file='assets/c_zadak_ddr5.png')
        self.c_203 = PhotoImage(
            file='assets/c_kingston_ddr5.png')
        self.c_300 = PhotoImage(
            file='assets/c_rtx_4090.png')
        self.c_301 = PhotoImage(
            file='assets/c_rtx_3050.png')
        self.c_302 = PhotoImage(
            file='assets/c_rx_7900xt.png')
        self.c_303 = PhotoImage(
            file='assets/c_rx_6650xt.png')
        self.c_400 = PhotoImage(
            file='assets/c_pmae_b650.png')
        self.c_401 = PhotoImage(
            file='assets/c_pmae_b550m.png')
        self.c_402 = PhotoImage(
            file='assets/c_pmae_h610m.png')
        self.c_403 = PhotoImage(
            file='assets/c_pmae_b560m.png')
        self.c_500 = PhotoImage(
            file='assets/c_hdd_purple.png')
        self.c_501 = PhotoImage(
            file='assets/c_hdd_blue.png')
        self.c_502 = PhotoImage(
            file='assets/c_ssd_kingston.png')
        self.c_503 = PhotoImage(
            file='assets/c_ssd_green.png')
        self.c_600 = PhotoImage(
            file='assets/c_f_thermaltake_t.png')
        self.c_601 = PhotoImage(
            file='assets/c_f_thermaltake_s.png')
        self.c_602 = PhotoImage(
            file='assets/c_f_scoolerm.png')
        self.c_603 = PhotoImage(
            file='assets/c_f_reddragon.png')
        self.bt_sair = PhotoImage(file='assets/bt_sair.png')
        self.bt_voltar = PhotoImage(file='assets/bt_voltar.png')
